Repository cs361w2019-osu/sprint1-group-10, pull requests merged in 2019-02, with the labels that each got.

#74 Positioning
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement

#88 Sonar is finished and test functions are in #86
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/controllers/ApplicationController.java
  src/main/java/controllers/AttackGameAction.java
  src/main/java/cs361/battleships/models/AtackStatus.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
  src/main/java/cs361/battleships/models/Square.java
  src/main/java/views/ApplicationController/index.ftl.html
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: feature

#90 Adding Travis CI
  .gitignore
  .travis.yml
Labels: enhancement

#91 beatiful
  footer.ftl.html
  index.ftl.html
Labels: enhancement

#96 James PR
  src/main/java/cs361/battleships/models/Result.java
Labels: enhancement, feature
